server:
  port: 80
spring:
  application:
    name: app-cnshop-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
zuul:
  routes:
    api-a:
      path: /api-weixin/**
      serviceId: app-cnshop-weixin
    api-b:
      path: /api-number/**
      serviceId: app-cnshop-number
