logging:
  level:
    org.springframework.web: INFO
    com.cnshop.weixin.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wx2dd67b13e3c2e7ed #（一个公众号的appid）
        secret: d4e619044fae52fab67ea81af6478947 #（公众号的appsecret）
        token: cnshop #（接口配置里的Token值
server:
    port: 8200

cnshop:
  weixin:
    registration:
       code:
       ###微信注册码消息
        message:  您的注册码为:%s，请关注<a href="http://huanglei.natapp4.cc">菜鸟购物</a>，里面超多优惠等着你，期待你的加入，感谢！
    ###默认提示消息
    default:
      registration:
        code:
          message: 您的消息，我们已经收到,会及时回复给您的!

spring:
  redis:
    host: 120.79.136.84
    port: 6379
    jedis:
      pool:
        max-active: 100
        min-idle: 1
        max-idle: 100
        max-wait: -1